export const GET_LIST_PUBLISHER_REQUESTED: string = 'GET_LIST_PUBLISHER_REQUESTED';
export const GET_LIST_PUBLISHER_SUCCESS: string = 'GET_LIST_PUBLISHER_SUCCESS';
export const GET_LIST_PUBLISHER_FAILED: string = 'GET_LIST_PUBLISHER_FAILED';

export const GET_ITEM_PUBLISHER_REQUESTED: string = 'GET_ITEM_PUBLISHER_REQUESTED';
export const GET_ITEM_PUBLISHER_SUCCESS: string = 'GET_ITEM_PUBLISHER_SUCCESS';
export const GET_ITEM_PUBLISHER_FAILED: string = 'GET_ITEM_PUBLISHER_FAILED';

export const CREATE_PUBLISHER_REQUESTED: string = 'CREATE_PUBLISHER_REQUESTED';
export const CREATE_PUBLISHER_SUCCESS: string = 'CREATE_PUBLISHER_SUCCESS';
export const CREATE_PUBLISHER_FAILED: string = 'CREATE_PUBLISHER_FAILED';

export const EDIT_PUBLISHER_REQUESTED: string = 'EDIT_PUBLISHER_REQUESTED';
export const EDIT_PUBLISHER_SUCCESS: string = 'EDIT_PUBLISHER_SUCCESS';
export const EDIT_PUBLISHER_FAILED: string = 'EDIT_PUBLISHER_FAILED';

export const DELETE_PUBLISHER_REQUESTED: string = 'DELETE_PUBLISHER_REQUESTED';
export const DELETE_PUBLISHER_SUCCESS: string = 'DELETE_PUBLISHER_SUCCESS';
export const DELETE_PUBLISHER_FAILED: string = 'DELETE_PUBLISHER_FAILED';

export const REMOVE_CURRENT_PUBLISHER: string = 'REMOVE_CURRENT_PUBLISHER';
export const REMOVE_MESSAGE: string = 'REMOVE_MESSAGE';
