export const GET_LIST_ORDER_REQUESTED: string = 'GET_LIST_ORDER_REQUESTED';
export const GET_LIST_ORDER_SUCCESS: string = 'GET_LIST_ORDER_SUCCESS';
export const GET_LIST_ORDER_FAILED: string = 'GET_LIST_ORDER_FAILED';

export const GET_ITEM_ORDER_REQUESTED: string = 'GET_ITEM_ORDER_REQUESTED';
export const GET_ITEM_ORDER_SUCCESS: string = 'GET_ITEM_ORDER_SUCCESS';
export const GET_ITEM_ORDER_FAILED: string = 'GET_ITEM_ORDER_FAILED';

export const CREATE_ORDER_REQUESTED: string = 'CREATE_ORDER_REQUESTED';
export const CREATE_ORDER_SUCCESS: string = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILED: string = 'CREATE_ORDER_FAILED';

export const EDIT_ORDER_REQUESTED: string = 'EDIT_ORDER_REQUESTED';
export const EDIT_ORDER_SUCCESS: string = 'EDIT_ORDER_SUCCESS';
export const EDIT_ORDER_FAILED: string = 'EDIT_ORDER_FAILED';

export const DELETE_ORDER_REQUESTED: string = 'DELETE_ORDER_REQUESTED';
export const DELETE_ORDER_SUCCESS: string = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILED: string = 'DELETE_ORDER_FAILED';

export const REMOVE_CURRENT_ORDER: string = 'REMOVE_CURRENT_ORDER';
export const REMOVE_MESSAGE: string = 'REMOVE_MESSAGE';
