export const GET_LIST_CATEGORY_REQUESTED: string =
  'GET_LIST_CATEGORY_REQUESTED';
export const GET_LIST_CATEGORY_SUCCESS: string = 'GET_LIST_CATEGORY_SUCCESS';
export const GET_LIST_CATEGORY_FAILED: string = 'GET_LIST_CATEGORY_FAILED';

export const GET_LIST_PARENT_CATEGORY_REQUESTED: string =
  'GET_LIST_PARENT_CATEGORY_REQUESTED';
export const GET_LIST_PARENT_CATEGORY_SUCCESS: string =
  'GET_LIST_PARENT_CATEGORY_SUCCESS';
export const GET_LIST_PARENT_CATEGORY_FAILED: string =
  'GET_LIST_PARENT_CATEGORY_FAILED';

export const GET_ITEM_CATEGORY_REQUESTED: string =
  'GET_ITEM_CATEGORY_REQUESTED';
export const GET_ITEM_CATEGORY_SUCCESS: string = 'GET_ITEM_CATEGORY_SUCCESS';
export const GET_ITEM_CATEGORY_FAILED: string = 'GET_ITEM_CATEGORY_FAILED';

export const CREATE_CATEGORY_REQUESTED: string = 'CREATE_CATEGORY_REQUESTED';
export const CREATE_CATEGORY_SUCCESS: string = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILED: string = 'CREATE_CATEGORY_FAILED';

export const EDIT_CATEGORY_REQUESTED: string = 'EDIT_CATEGORY_REQUESTED';
export const EDIT_CATEGORY_SUCCESS: string = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_FAILED: string = 'EDIT_CATEGORY_FAILED';

export const DELETE_CATEGORY_REQUESTED: string = 'DELETE_CATEGORY_REQUESTED';
export const DELETE_CATEGORY_SUCCESS: string = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED: string = 'DELETE_CATEGORY_FAILED';

export const REMOVE_CURRENT_CATEGORY: string = 'REMOVE_CURRENT_CATEGORY';
export const REMOVE_MESSAGE: string = 'REMOVE_MESSAGE';
