export const GET_LIST_AUTHOR_REQUESTED: string = 'GET_LIST_AUTHOR_REQUESTED';
export const GET_LIST_AUTHOR_SUCCESS: string = 'GET_LIST_AUTHOR_SUCCESS';
export const GET_LIST_AUTHOR_FAILED: string = 'GET_LIST_AUTHOR_FAILED';

export const GET_ITEM_AUTHOR_REQUESTED: string = 'GET_ITEM_AUTHOR_REQUESTED';
export const GET_ITEM_AUTHOR_SUCCESS: string = 'GET_ITEM_AUTHOR_SUCCESS';
export const GET_ITEM_AUTHOR_FAILED: string = 'GET_ITEM_AUTHOR_FAILED';

export const CREATE_AUTHOR_REQUESTED: string = 'CREATE_AUTHOR_REQUESTED';
export const CREATE_AUTHOR_SUCCESS: string = 'CREATE_AUTHOR_SUCCESS';
export const CREATE_AUTHOR_FAILED: string = 'CREATE_AUTHOR_FAILED';

export const EDIT_AUTHOR_REQUESTED: string = 'EDIT_AUTHOR_REQUESTED';
export const EDIT_AUTHOR_SUCCESS: string = 'EDIT_AUTHOR_SUCCESS';
export const EDIT_AUTHOR_FAILED: string = 'EDIT_AUTHOR_FAILED';

export const DELETE_AUTHOR_REQUESTED: string = 'DELETE_AUTHOR_REQUESTED';
export const DELETE_AUTHOR_SUCCESS: string = 'DELETE_AUTHOR_SUCCESS';
export const DELETE_AUTHOR_FAILED: string = 'DELETE_AUTHOR_FAILED';

export const REMOVE_CURRENT_AUTHOR: string = 'REMOVE_CURRENT_AUTHOR';
export const REMOVE_MESSAGE: string = 'REMOVE_MESSAGE';
