export const GET_LIST_COUPON_REQUESTED: string = 'GET_LIST_COUPON_REQUESTED';
export const GET_LIST_COUPON_SUCCESS: string = 'GET_LIST_COUPON_SUCCESS';
export const GET_LIST_COUPON_FAILED: string = 'GET_LIST_COUPON_FAILED';

export const GET_ITEM_COUPON_REQUESTED: string = 'GET_ITEM_COUPON_REQUESTED';
export const GET_ITEM_COUPON_SUCCESS: string = 'GET_ITEM_COUPON_SUCCESS';
export const GET_ITEM_COUPON_FAILED: string = 'GET_ITEM_COUPON_FAILED';

export const CREATE_COUPON_REQUESTED: string = 'CREATE_COUPON_REQUESTED';
export const CREATE_COUPON_SUCCESS: string = 'CREATE_COUPON_SUCCESS';
export const CREATE_COUPON_FAILED: string = 'CREATE_COUPON_FAILED';

export const EDIT_COUPON_REQUESTED: string = 'EDIT_COUPON_REQUESTED';
export const EDIT_COUPON_SUCCESS: string = 'EDIT_COUPON_SUCCESS';
export const EDIT_COUPON_FAILED: string = 'EDIT_COUPON_FAILED';

export const DELETE_COUPON_REQUESTED: string = 'DELETE_COUPON_REQUESTED';
export const DELETE_COUPON_SUCCESS: string = 'DELETE_COUPON_SUCCESS';
export const DELETE_COUPON_FAILED: string = 'DELETE_COUPON_FAILED';

export const REMOVE_CURRENT_COUPON: string = 'REMOVE_CURRENT_COUPON';
export const REMOVE_MESSAGE: string = 'REMOVE_MESSAGE';
