export const TOGGLE_NAVBAR_DROPDOWN: string = 'TOGGLE_NAVBAR_DROPDOWN';
export const TOGGLE_NAVBAR_MOBILE: string = 'TOGGLE_NAVBAR_MOBILE';
export const TOGGLE_NAVBAR_MENU_MOBILE: string = 'TOGGLE_NAVBAR_MENU_MOBILE';
