export const GET_LIST_USER_REQUESTED: string = 'GET_LIST_USER_REQUESTED';
export const GET_LIST_USER_SUCCESS: string = 'GET_LIST_USER_SUCCESS';
export const GET_LIST_USER_FAILED: string = 'GET_LIST_USER_FAILED';

export const GET_ITEM_USER_REQUESTED: string = 'GET_ITEM_USER_REQUESTED';
export const GET_ITEM_USER_SUCCESS: string = 'GET_ITEM_USER_SUCCESS';
export const GET_ITEM_USER_FAILED: string = 'GET_ITEM_USER_FAILED';

export const CREATE_USER_REQUESTED: string = 'CREATE_USER_REQUESTED';
export const CREATE_USER_SUCCESS: string = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED: string = 'CREATE_USER_FAILED';

export const EDIT_USER_REQUESTED: string = 'EDIT_USER_REQUESTED';
export const EDIT_USER_SUCCESS: string = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILED: string = 'EDIT_USER_FAILED';

export const DELETE_USER_REQUESTED: string = 'DELETE_USER_REQUESTED';
export const DELETE_USER_SUCCESS: string = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED: string = 'DELETE_USER_FAILED';

export const REMOVE_CURRENT_USER: string = 'REMOVE_CURRENT_USER';
export const REMOVE_MESSAGE: string = 'REMOVE_MESSAGE';
